version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:3001

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/local.env
    depends_on:
      - db
    environment:
      - DB_HOST=db

  db:
    image: postgres
    restart: always
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data:
